# Let NetworkManager manage all devices on this system
network:
  ethernets:
    eth0:
      dhcp4: true
      dhcp6: no
      addresses: [192.168.8.190/24, ]
      gateway4: 192.168.8.8
      nameservers:
        addresses: [192.168.8.8, ]
  version: 2

  renderer: NetworkManager
