# Let NetworkManager manage all devices on this system
network:
  ethernets:
    eth0:
      dhcp4: true
      dhcp6: no
      addresses: [192.168.1.190/24, ]
      gateway4: 192.168.1.1
      nameservers:
        addresses: [192.168.1.1, ]
  version: 2

  renderer: NetworkManager
